# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]  # adjust if you deploy from a different branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (TypeScript -> dist/)
        run: npm run build

      # Make a minimal prod bundle: dist/ + package.json + prod node_modules
      - name: Prepare deploy folder
        run: |
          rm -rf deploy release.zip
          mkdir -p deploy
          cp package*.json deploy/
          cp -r dist deploy/dist
          cd deploy
          npm ci --omit=dev
          cd ..
          (cd deploy && zip -r ../release.zip .)

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: mdcs            # <-- your Web App name
          slot-name: Production
          package: release.zip     
